# Generated by Django 4.1.7 on 2023-03-17 16:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pipelines', '0004_pipelinesource_owner'),
        ('core', '0005_alter_openaikey_options_alter_openaikey_date_created_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dblogs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LogEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fn_name', models.CharField(max_length=100)),
                ('fn_type', models.CharField(choices=[('builtin', 'Built-in'), ('prompt', 'Prompt')], max_length=10)),
                ('pipeline_execution_id', models.IntegerField()),
                ('parameters', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='PipelineExecution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField(auto_now_add=True)),
                ('end_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('success', 'Executed successfully'), ('error', 'Errors')], max_length=10)),
                ('parameters', models.JSONField()),
                ('output', models.TextField()),
                ('error', models.TextField()),
                ('openai_key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.openaikey')),
                ('pipeline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pipelines.pipelinesource')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='LogMessage',
        ),
    ]
