# Generated by Django 4.1.7 on 2023-03-20 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dblogs', '0002_logentry_pipelineexecution_delete_logmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='logentry',
            name='output',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
