# Generated by Django 4.1.7 on 2023-03-20 12:36

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pipelines', '0004_pipelinesource_owner'),
        ('core', '0005_alter_openaikey_options_alter_openaikey_date_created_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dblogs', '0003_logentry_output'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='LogEntry',
            new_name='CallEntryLog',
        ),
        migrations.RenameModel(
            old_name='PipelineExecution',
            new_name='PipelineExecutionLog',
        ),
    ]
