# Generated by Django 4.1.7 on 2023-03-20 15:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dblogs', '0004_rename_logentry_callentrylog_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='callentrylog',
            name='end_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='callentrylog',
            name='start_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
