# Generated by Django 4.1.7 on 2023-11-30 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dblogs', '0005_callentrylog_end_date_callentrylog_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='callentrylog',
            name='completion_tokens',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='callentrylog',
            name='full_response',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='callentrylog',
            name='prompt_tokens',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
