# Generated by Django 4.1.7 on 2023-11-30 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dblogs', '0006_callentrylog_completion_tokens_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pipelineexecutionlog',
            name='total_completion_tokens',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pipelineexecutionlog',
            name='total_prompt_tokens',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pipelineexecutionlog',
            name='total_tokens',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
