# Generated by Django 4.1.7 on 2023-12-26 19:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dblogs', '0007_pipelineexecutionlog_total_completion_tokens_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pipelineexecutionlog',
            old_name='openai_key',
            new_name='apikey',
        ),
    ]
