# Generated by Django 4.1.7 on 2023-12-26 21:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_publictoken_alias'),
        ('dblogs', '0008_rename_openai_key_pipelineexecutionlog_apikey'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pipelineexecutionlog',
            name='apikey',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.publictoken'),
        ),
    ]
