# Generated by Django 4.1.7 on 2023-12-26 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dblogs', '0009_alter_pipelineexecutionlog_apikey'),
    ]

    operations = [
        migrations.AddField(
            model_name='callentrylog',
            name='completion_cost',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='callentrylog',
            name='prompt_cost',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pipelineexecutionlog',
            name='total_completion_cost',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pipelineexecutionlog',
            name='total_cost',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pipelineexecutionlog',
            name='total_prompt_cost',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
