# Generated by Django 4.1.7 on 2023-12-26 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dblogs', '0010_callentrylog_completion_cost_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='callentrylog',
            name='model',
            field=models.CharField(max_length=79, null=True),
        ),
    ]
