# Generated by Django 4.1.7 on 2024-01-19 22:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_alter_publictoken_openaikey_and_more'),
        ('dblogs', '0011_callentrylog_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pipelineexecutionlog',
            name='apikey',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='execution_logs', to='core.publictoken'),
        ),
    ]
