# Generated by Django 4.1.5 on 2023-02-23 15:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BuiltinFunction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='date created')),
                ('date_updated', models.DateTimeField(auto_now=True, verbose_name='date updated')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this object should be treated as active. Unselect this instead of deleting objects.', verbose_name='active')),
                ('name', models.CharField(choices=[('concat', 'concat'), ('now', 'now'), ('identity', 'identity')], max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Builtin Function',
                'verbose_name_plural': 'Builtin Functions',
            },
        ),
        migrations.CreateModel(
            name='PipelineSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='date created')),
                ('date_updated', models.DateTimeField(auto_now=True, verbose_name='date updated')),
                ('body', models.TextField()),
            ],
            options={
                'verbose_name': 'PipelineSource',
                'verbose_name_plural': 'PipelineSources',
            },
        ),
        migrations.CreateModel(
            name='Prompt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='date created')),
                ('date_updated', models.DateTimeField(auto_now=True, verbose_name='date updated')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this object should be treated as active. Unselect this instead of deleting objects.', verbose_name='active')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('body', models.TextField()),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Prompt',
                'verbose_name_plural': 'Prompts',
            },
        ),
        migrations.CreateModel(
            name='DAGNode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.IntegerField(choices=[(0, 'Prompt'), (1, 'Builtin Function'), (2, 'Placeholder')], default=0)),
                ('identifier', models.PositiveIntegerField()),
                ('name', models.CharField(max_length=150)),
                ('pipeline_source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nodes', to='pipelines.pipelinesource')),
            ],
            options={
                'verbose_name': 'DAGNode',
                'verbose_name_plural': 'DAGNodes',
            },
        ),
        migrations.CreateModel(
            name='DAGEdge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_edges', to='pipelines.dagnode')),
                ('to_node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_edges', to='pipelines.dagnode')),
            ],
            options={
                'verbose_name': 'DAGEdge',
                'verbose_name_plural': 'DAGEdges',
            },
        ),
        migrations.AddConstraint(
            model_name='dagnode',
            constraint=models.UniqueConstraint(fields=('type', 'name', 'identifier', 'pipeline_source'), name='unique_dagnodes'),
        ),
    ]
