# Generated by Django 4.1.7 on 2023-03-07 09:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import pipelines.validators


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pipelines', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='builtinfunction',
            name='name',
            field=models.CharField(choices=[('concat', 'concat'), ('now', 'now'), ('identity', 'identity')], max_length=100, unique=True, validators=[pipelines.validators.FunctionNameValidator()]),
        ),
        migrations.AlterField(
            model_name='prompt',
            name='name',
            field=models.CharField(max_length=100, unique=True, validators=[pipelines.validators.FunctionNameValidator()]),
        ),
        migrations.AlterField(
            model_name='prompt',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='author of the prompt'),
        ),
    ]
