# Generated by Django 4.1.5 on 2023-02-24 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pipelines', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='builtinfunction',
            name='name',
            field=models.CharField(choices=[('concat', 'concat'), ('now', 'now'), ('identity', 'identity'), ('call_builtin_function', 'call_builtin_function')], max_length=100, unique=True),
        ),
    ]
