# Generated by Django 4.1.5 on 2023-02-22 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pipelines', '0002_remove_builtinfunction_arity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='builtinfunction',
            name='name',
            field=models.CharField(choices=[('builtin_fn1', 'builtin_fn1'), ('builtin_fn2', 'builtin_fn2'), ('builtin_fn3', 'builtin_fn3'), ('get_arity_of_function', 'get_arity_of_function')], max_length=100, unique=True),
        ),
    ]
