# Generated by Django 4.1.7 on 2023-03-09 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pipelines', '0002_alter_builtinfunction_name_alter_prompt_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='builtinfunction',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='prompt',
            name='is_active',
        ),
    ]
