# Generated by Django 4.1.7 on 2023-03-10 08:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pipelines', '0003_remove_builtinfunction_is_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pipelinesource',
            name='owner',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Author of the Pipeline'),
            preserve_default=False,
        ),
    ]
