# Generated by Django 4.1.7 on 2023-03-23 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pipelines', '0004_pipelinesource_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='pipelinesource',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
