# Generated by Django 4.1.5 on 2023-02-22 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pipelines', '0004_alter_builtinfunction_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='builtinfunction',
            name='name',
            field=models.CharField(choices=[('concat', 'concat'), ('now', 'now')], max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='dagnode',
            name='type',
            field=models.IntegerField(choices=[(0, 'Prompt'), (1, 'Builtin Function'), (2, 'Placeholder')], default=0),
        ),
    ]
