# Generated by Django 4.1.5 on 2023-02-22 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pipelines', '0005_alter_builtinfunction_name_alter_dagnode_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dagnode',
            name='full_name',
            field=models.TextField(),
        ),
    ]
