# Generated by Django 4.1.7 on 2023-03-23 07:36

from django.db import migrations


def populate_pipelines_name_field(apps, schema_editor):
    cnt = 1
    PipelineSourceModel = apps.get_model('pipelines.PipelineSource')
    for pipeline in PipelineSourceModel.objects.all():
        pipeline.name = f"pipeline_{cnt}"
        pipeline.save()
        cnt += 1


class Migration(migrations.Migration):

    dependencies = [
        ('pipelines', '0005_pipelinesource_name'),
    ]

    operations = [
        migrations.RunPython(populate_pipelines_name_field, migrations.RunPython.noop),
    ]
