# Generated by Django 4.1.7 on 2023-03-23 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pipelines', '0006_auto_20230323_0736'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pipelinesource',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
