# Generated by Django 4.1.5 on 2023-02-23 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pipelines', '0006_alter_dagnode_full_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='builtinfunction',
            name='name',
            field=models.CharField(choices=[('concat', 'concat'), ('now', 'now'), ('identity', 'identity')], max_length=100, unique=True),
        ),
    ]
