# Generated by Django 4.1.7 on 2023-03-24 07:55

from django.db import migrations, models
import pipelines.validators


class Migration(migrations.Migration):

    dependencies = [
        ('pipelines', '0007_alter_pipelinesource_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='builtinfunction',
            name='name',
            field=models.CharField(max_length=100, unique=True, validators=[pipelines.validators.FunctionNameValidator()]),
        ),
    ]
