# Generated by Django 4.1.7 on 2023-11-08 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pipelines', '0008_alter_builtinfunction_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='prompt',
            name='type',
            field=models.IntegerField(choices=[(0, '3.5-turbo'), (1, '4-turbo')], default=0),
        ),
    ]
