# Generated by Django 4.1.7 on 2023-11-08 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pipelines', '0010_alter_prompt_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prompt',
            name='type',
            field=models.IntegerField(choices=[(0, 'gpt-3.5-turbo-1106'), (1, 'gpt-4-1106-preview')], default=0),
        ),
    ]
