# Generated by Django 4.1.7 on 2023-11-27 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pipelines', '0011_alter_prompt_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='OpenAIDocument',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('object_type', models.CharField(max_length=50)),
                ('bytes', models.PositiveIntegerField()),
                ('filename', models.CharField(max_length=255)),
                ('purpose', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField()),
            ],
        ),
    ]
