# Generated by Django 4.1.7 on 2023-11-28 01:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pipelines', '0012_openaidocument'),
    ]

    operations = [
        migrations.AddField(
            model_name='openaidocument',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to=settings.AUTH_USER_MODEL, verbose_name='Author of the Document'),
            preserve_default=False,
        ),
    ]
