# Generated by Django 4.1.7 on 2023-11-28 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pipelines', '0013_openaidocument_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='openaidocument',
            name='original_filename',
            field=models.CharField(default=models.CharField(max_length=255), max_length=255),
        ),
    ]
