# Generated by Django 4.1.7 on 2023-11-28 15:03

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pipelines', '0014_openaidocument_original_filename'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OpenAIDocument',
            new_name='Document',
        ),
    ]
