# Generated by Django 4.1.7 on 2023-11-29 00:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pipelines', '0015_rename_openaidocument_document'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to=settings.AUTH_USER_MODEL, verbose_name='Author of the Document'),
        ),
        migrations.CreateModel(
            name='Assistant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('openai_id', models.CharField(max_length=255, unique=True)),
                ('name', models.CharField(max_length=256)),
                ('original_name', models.CharField(max_length=256)),
                ('description', models.TextField(blank=True, max_length=512, null=True)),
                ('model', models.CharField(max_length=64)),
                ('instructions', models.TextField(blank=True, max_length=32768, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.IntegerField()),
                ('files', models.ManyToManyField(blank=True, to='pipelines.document')),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assistants', to=settings.AUTH_USER_MODEL, verbose_name='Author of the Assistant')),
            ],
        ),
    ]
