# Generated by Django 4.1.7 on 2023-11-29 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pipelines', '0016_alter_document_owner_assistant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assistant',
            name='created_at',
        ),
    ]
