# Generated by Django 4.1.7 on 2023-11-29 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pipelines', '0017_remove_assistant_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='assistant',
            name='created_at',
            field=models.DateTimeField(default=None),
        ),
    ]
