# Generated by Django 4.1.7 on 2023-11-30 00:33

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('pipelines', '0018_assistant_created_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assistant',
            old_name='original_name',
            new_name='prefixed_name',
        ),
    ]
