# Generated by Django 4.1.7 on 2023-12-22 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pipelines', '0019_rename_original_name_assistant_prefixed_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prompt',
            name='type',
            field=models.CharField(choices=[('gpt-4-1106', 'GPT-4 Turbo 1106'), ('gpt-4-1106-vision-preview', 'GPT-4 1106 Vision Preview'), ('gpt-4', 'GPT-4'), ('gpt-4-32k', 'GPT-4 32K'), ('gpt-3.5-turbo-1106', 'GPT-3.5 Turbo 1106'), ('gpt-3.5-turbo-instruct', 'GPT-3.5 Turbo Instruct'), ('mistral-7b-instruct-v0.2', 'Mistral 7B Instruct v0.2'), ('mixtral-8x7b-instruct', 'Mixtral 8x7B Instruct'), ('mixtral-8x7b', 'Mixtral 8x7B')], max_length=50),
        ),
    ]
