# Generated by Django 4.1.7 on 2023-12-27 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pipelines', '0021_alter_prompt_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prompt',
            name='type',
            field=models.CharField(choices=[('gpt-4-1106-preview', 'GPT-4 Turbo 1106'), ('gpt-4-1106-vision-preview', 'GPT-4 1106 Vision Preview'), ('gpt-4', 'GPT-4'), ('gpt-4-32k', 'GPT-4 32K'), ('gpt-3.5-turbo-1106', 'GPT-3.5 Turbo 1106'), ('gpt-3.5-turbo-instruct', 'GPT-3.5 Turbo Instruct'), ('mistralai/Mistral-7B-Instruct-v0.2', 'Mistral (7B) Instruct v0.2\t'), ('mistralai/Mixtral-8x7B-Instruct-v0.1', 'Mixtral 8x7B Instruct'), ('mistralai/Mixtral-8x7B-v0.1', 'Mixtral MoE 8x7B\t')], max_length=50),
        ),
    ]
