# Generated by Django 4.1.7 on 2024-05-07 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pipelines', '0024_alter_prompt_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='prompt',
            name='json_mode',
            field=models.BooleanField(default=False),
        ),
    ]
