version: '3.8'

services:
  db:
    container_name: aieye-db
    image: postgres:12
    volumes:
      - db_data:/var/lib/postgresql/data
    env_file:
      - ./.env
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    networks:
      - aieye_network

  web:
    container_name: aieye-web
    build: .
    command: bash -c "python manage.py migrate && gunicorn configs.wsgi:application --bind 0.0.0.0:8000 -w 3 --timeout 600 --worker-class gevent"
    volumes:
      - .:/ai-eye
      - /tmp/eval:/eval
      - /var/run/docker.sock:/var/run/docker.sock
      - static_volume:/ai-eye/staticfiles
    ports:
      - "8000:8000"
    env_file:
      - ./.env
    depends_on:
      - db
    links:
      - db:db
    networks:
      - aieye_network

  eval:
    build:
      context: .
      dockerfile: Dockerfile.eval
    environment:
      - FILE_NAME=${FILE_NAME}
    volumes:
      - /tmp/eval:/eval

volumes:
  db_data: { }
  static_volume: { }

networks:
  aieye_network:
    driver: bridge
