# Generated by Django 4.1.5 on 2023-02-03 09:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0005_alter_openaikey_options_alter_openaikey_date_created_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_type', models.CharField(max_length=50)),
                ('endpoint', models.CharField(max_length=100)),
                ('method', models.CharField(max_length=10)),
                ('parameters', models.TextField()),
                ('response', models.TextField()),
                ('cache_hit', models.BooleanField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('expire_time', models.DateTimeField()),
                ('api_key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.openaikey')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Log',
                'verbose_name_plural': 'Logs',
            },
        ),
    ]
