# Generated by Django 4.1.5 on 2023-02-03 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='parameters',
            field=models.TextField(db_index=True),
        ),
    ]
