# Generated by Django 4.1.5 on 2023-02-03 18:10

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_log_parameters'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='expire_time',
            field=models.DateTimeField(default=api.models.get_expire_time),
        ),
    ]
