# Generated by Django 4.1.5 on 2023-02-13 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_log_parameters'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='log',
            name='api_type',
        ),
    ]
