# Generated by Django 4.1.5 on 2023-02-07 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_log_expire_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='log',
            name='expire_time',
        ),
        migrations.RemoveField(
            model_name='log',
            name='method',
        ),
    ]
