# Generated by Django 4.1.5 on 2023-02-15 16:19

from django.db import migrations, models


def clear_logs_table(apps, schema_editor):
    Log = apps.get_model("api", "Log")
    Log.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_log_api_type'),
    ]

    operations = [
        migrations.RunPython(clear_logs_table),
        migrations.AlterField(
            model_name='log',
            name='parameters',
            field=models.JSONField(),
        ),
    ]
