# Generated by Django 4.1.7 on 2024-01-19 22:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_alter_publictoken_openaikey_and_more'),
        ('api', '0004_alter_log_parameters'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='api_key',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.apikey'),
        ),
    ]
