# Generated by Django 4.1.5 on 2023-01-31 12:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_openaikey'),
    ]

    operations = [
        migrations.AlterField(
            model_name='openaikey',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='openaikeys', to=settings.AUTH_USER_MODEL),
        ),
    ]
