# Generated by Django 4.1.5 on 2023-02-01 10:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_openaikey_publictoken_openaikey_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publictoken',
            name='key',
            field=models.CharField(db_index=True, max_length=40, unique=True, validators=[django.core.validators.MinLengthValidator(40), django.core.validators.MaxLengthValidator(40)], verbose_name='Key'),
        ),
    ]
