# Generated by Django 4.1.7 on 2023-12-22 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_openaikey_options_alter_openaikey_date_created_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='openaikey',
            options={'verbose_name': 'API key', 'verbose_name_plural': 'API keys'},
        ),
        migrations.AddField(
            model_name='openaikey',
            name='service',
            field=models.CharField(choices=[('openai', 'OpenAI'), ('togetherai', 'TogetherAI')], default='openai', max_length=50),
            preserve_default=False,
        ),
    ]
