# Generated by Django 4.1.7 on 2023-12-22 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_openaikey_options_openaikey_service'),
    ]

    operations = [
        migrations.RenameField(
            model_name='publictoken',
            old_name='openaikey',
            new_name='apikey',
        ),
        migrations.AlterUniqueTogether(
            name='publictoken',
            unique_together={('user', 'apikey')},
        ),
    ]
