# Generated by Django 4.1.7 on 2023-12-22 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dblogs', '0007_pipelineexecutionlog_total_completion_tokens_and_more'),
        ('api', '0004_alter_log_parameters'),
        ('core', '0007_rename_openaikey_publictoken_apikey_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OpenAIKey',
            new_name='APIKey',
        ),
    ]
