# Generated by Django 4.1.7 on 2023-12-24 00:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_rename_openaikey_apikey'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apikey',
            name='is_active',
        ),
    ]
