# Generated by Django 4.1.7 on 2023-12-24 00:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_remove_apikey_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apikey',
            name='users',
        ),
        migrations.AlterField(
            model_name='publictoken',
            name='apikey',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='openai_tokens', to='core.apikey'),
        ),
    ]
