# Generated by Django 4.1.7 on 2023-12-24 00:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_remove_apikey_users_alter_publictoken_apikey'),
    ]

    operations = [
        migrations.RenameField(
            model_name='publictoken',
            old_name='apikey',
            new_name='openaikey',
        ),
        migrations.AlterUniqueTogether(
            name='publictoken',
            unique_together={('user', 'openaikey')},
        ),
    ]
