# Generated by Django 4.1.7 on 2023-12-24 00:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_rename_apikey_publictoken_openaikey_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='publictoken',
            unique_together={('user', 'openaikey')},
        ),
        migrations.AddField(
            model_name='publictoken',
            name='togetheraikey',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='togetherai_tokens', to='core.apikey'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='publictoken',
            unique_together={('user', 'openaikey'), ('user', 'togetheraikey')},
        ),
    ]
