# Generated by Django 4.1.7 on 2023-12-24 01:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_publictoken_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publictoken',
            name='openaikey',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='openai_tokens', to='core.apikey'),
        ),
    ]
