# Generated by Django 4.1.7 on 2023-12-26 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_alter_publictoken_openaikey'),
    ]

    operations = [
        migrations.AddField(
            model_name='publictoken',
            name='alias',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='Alias'),
        ),
    ]
