# Generated by Django 4.1.7 on 2024-01-16 16:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_publictoken_alias'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apikey',
            name='owner',
            field=models.ForeignKey(help_text="Designates a user who issued this API Key. It's supposed to be an AIEYE_ADMIN user", on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
