# Generated by Django 4.1.7 on 2024-01-19 22:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_alter_apikey_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publictoken',
            name='openaikey',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='openai_tokens', to='core.apikey'),
        ),
        migrations.AlterField(
            model_name='publictoken',
            name='togetheraikey',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='togetherai_tokens', to='core.apikey'),
        ),
    ]
